title: "Futurist Human Totem: Tell me something I don't know"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.488806
  brandStrength: 0.8138317330740392
  lightness: 0.2285448
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  rhythmicContrast: 0.2961754
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Nancy Velasquez
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7322761
layout_spectrum: 0.389459
