title: "Futurist Human Totem: Tell me something I don't know"
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.488806
  brandStrength: 0.8138317330740392
  lightness: 0.4272388
  brandColors:
    - '#D5D5D5'
    - '#01008A'
    - '#130F03'
    - '#455248'
    - '#88A972'
  rhythmicContrast: 0.4421642
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Nancy Velasquez
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7322761
layout_spectrum: 0.389459
